CrudPolizas/Models/ErrorViewModel.cs
namespace CrudPolizas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudPolizas/Controllers/PolizaController.cs
using Models;
using Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CrudPolizas.Controllers
{
    public class PolizaController : Controller
    {
        private readonly IPoliza _ipoliza;

        public PolizaController(IPoliza ipoliza)
        {
            _ipoliza = ipoliza;
        }

        // GET: PolizaController
        public ActionResult Index()
        {
            var poliza = _ipoliza.Listar();
            return View(poliza);
        }

        // GET: PolizaController/Details/5
        public ActionResult Details(int id)
        {
            var poliza = _ipoliza.Obtener(id);
            return View(poliza);
        }

        // GET: PolizaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PolizaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Poliza poliza)
        {
            try
            {
                _ipoliza.Registrar(poliza);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PolizaController/Edit/5
        public ActionResult Edit(int id)
        {
            var poliza = _ipoliza.Obtener(id);
            return View(poliza);
        }

        // POST: PolizaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Poliza poliza)
        {
            try
            {
                _ipoliza.Modificar(poliza);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PolizaController/Delete/5
        public ActionResult Delete(int id)
        {
            var poliza = _ipoliza.Obtener(id);

            if(poliza == null)
                return NotFound();

            return View(poliza);
        }

        // POST: PolizaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmado(int numeroPoliza)
        {
            try
            {
                _ipoliza.Eliminar(numeroPoliza);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CrudPolizas/Views/Poliza/Create.cshtml
@model Models.Poliza

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Poliza</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroPoliza" class="control-label"></label>
                <input asp-for="NumeroPoliza" class="form-control" />
                <span asp-validation-for="NumeroPoliza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPoliza" class="control-label"></label>
                <input asp-for="FechaPoliza" class="form-control" />
                <span asp-validation-for="FechaPoliza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coberturas" class="control-label"></label>
                <input asp-for="Coberturas" class="form-control" />
                <span asp-validation-for="Coberturas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorMaximo" class="control-label"></label>
                <input asp-for="ValorMaximo" class="form-control" />
                <span asp-validation-for="ValorMaximo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePoliza" class="control-label"></label>
                <input asp-for="NombrePoliza" class="form-control" />
                <span asp-validation-for="NombrePoliza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CiudadResidencia" class="control-label"></label>
                <input asp-for="CiudadResidencia" class="form-control" />
                <span asp-validation-for="CiudadResidencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DireccionResidencia" class="control-label"></label>
                <input asp-for="DireccionResidencia" class="form-control" />
                <span asp-validation-for="DireccionResidencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacaAutomotor" class="control-label"></label>
                <input asp-for="PlacaAutomotor" class="form-control" />
                <span asp-validation-for="PlacaAutomotor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloAutomotor" class="control-label"></label>
                <input asp-for="ModeloAutomotor" class="form-control" />
                <span asp-validation-for="ModeloAutomotor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inspeccion" class="control-label"></label>
                <input asp-for="Inspeccion" class="form-control" />
                <span asp-validation-for="Inspeccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudPolizas/Views/Poliza/Delete.cshtml
@model Models.Poliza

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Poliza</h4>
    <hr />
    <form asp-action="DeleteConfirmado">
        <input type="hidden" asp-for="NumeroPoliza" />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coberturas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coberturas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorMaximo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorMaximo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombrePoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CiudadResidencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CiudadResidencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DireccionResidencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DireccionResidencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlacaAutomotor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlacaAutomotor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModeloAutomotor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloAutomotor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inspeccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inspeccion)
        </dd>
    </dl>
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CrudPolizas/Views/Poliza/Details.cshtml
@model Models.Poliza

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Poliza</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coberturas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coberturas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorMaximo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorMaximo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombrePoliza)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePoliza)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CiudadResidencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CiudadResidencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DireccionResidencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DireccionResidencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlacaAutomotor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlacaAutomotor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModeloAutomotor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloAutomotor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inspeccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inspeccion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NumeroPoliza }) |
    <a asp-action="Index">Back to List</a>
</div>

CrudPolizas/Views/Poliza/Edit.cshtml
@model Models.Poliza

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Poliza</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPoliza" class="control-label"></label>
                <input asp-for="FechaPoliza" class="form-control" />
                <span asp-validation-for="FechaPoliza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coberturas" class="control-label"></label>
                <input asp-for="Coberturas" class="form-control" />
                <span asp-validation-for="Coberturas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorMaximo" class="control-label"></label>
                <input asp-for="ValorMaximo" class="form-control" />
                <span asp-validation-for="ValorMaximo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePoliza" class="control-label"></label>
                <input asp-for="NombrePoliza" class="form-control" />
                <span asp-validation-for="NombrePoliza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CiudadResidencia" class="control-label"></label>
                <input asp-for="CiudadResidencia" class="form-control" />
                <span asp-validation-for="CiudadResidencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DireccionResidencia" class="control-label"></label>
                <input asp-for="DireccionResidencia" class="form-control" />
                <span asp-validation-for="DireccionResidencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacaAutomotor" class="control-label"></label>
                <input asp-for="PlacaAutomotor" class="form-control" />
                <span asp-validation-for="PlacaAutomotor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeloAutomotor" class="control-label"></label>
                <input asp-for="ModeloAutomotor" class="form-control" />
                <span asp-validation-for="ModeloAutomotor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inspeccion" class="control-label"></label>
                <input asp-for="Inspeccion" class="form-control" />
                <span asp-validation-for="Inspeccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudPolizas/Views/Poliza/Index.cshtml
@model IEnumerable<Models.Poliza>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPoliza)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coberturas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorMaximo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombrePoliza)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CiudadResidencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DireccionResidencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlacaAutomotor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeloAutomotor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inspeccion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPoliza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coberturas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorMaximo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombrePoliza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CiudadResidencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DireccionResidencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlacaAutomotor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeloAutomotor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inspeccion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.NumeroPoliza }) |
                @Html.ActionLink("Details", "Details", new { id=item.NumeroPoliza }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.NumeroPoliza })
            </td>
        </tr>
}
    </tbody>
</table>

CrudPolizas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudPolizas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudPolizas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Poliza" asp-action="Index">CrudPolizas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudPolizas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>